/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function PenguinBBQ({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/tRX-LctGY-DA-hiU/scene.splinecode')
  return (
    <>
      {/* <color attach="background" args={['#74757a']} /> */}
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <group name="CookingScene" position={[-17.53, 389.61, -535.41]}>
            <group name="mangal" position={[17.53, -228.76, 163.82]} scale={0.07}>
              <group name="Group 4" position={[60.7, 2406.65, 139.79]} scale={3.33}>
                <group name="Group 6" position={[77.18, -374.86, -107.61]} rotation={[0, 1.03, 0]} scale={0.14}>
                  <mesh
                    name="Cube 8"
                    geometry={nodes['Cube 8'].geometry}
                    material={materials['Cube 8 Material']}
                    castShadow
                    receiveShadow
                    position={[119.9, -472.12, 148.86]}
                    rotation={[-Math.PI / 2, 0, 1.47]}
                    scale={0.11}
                  />
                  <mesh
                    name="Cube 81"
                    geometry={nodes['Cube 81'].geometry}
                    material={materials['Cube 81 Material']}
                    castShadow
                    receiveShadow
                    position={[-142.35, -229.37, 115.44]}
                    rotation={[-Math.PI / 2, 0, -1.31]}
                    scale={0.18}
                  />
                  <mesh
                    name="Cube 82"
                    geometry={nodes['Cube 82'].geometry}
                    material={materials['Cube 82 Material']}
                    castShadow
                    receiveShadow
                    position={[-151.45, -22.25, -153.6]}
                    rotation={[-Math.PI / 2, 0, -0.38]}
                    scale={0.15}
                  />
                  <mesh
                    name="Cube 83"
                    geometry={nodes['Cube 83'].geometry}
                    material={materials['Cube 83 Material']}
                    castShadow
                    receiveShadow
                    position={[22.67, -273.31, -409.56]}
                    rotation={[-Math.PI / 2, 0, -1.07]}
                    scale={0.1}
                  />
                </group>
                <group
                  name="Group 5"
                  position={[-114.5, -342.04, -31.19]}
                  rotation={[-Math.PI, 1.48, Math.PI]}
                  scale={0.14}
                >
                  <mesh
                    name="Cube 84"
                    geometry={nodes['Cube 84'].geometry}
                    material={materials['Cube 84 Material']}
                    castShadow
                    receiveShadow
                    position={[119.9, -472.12, 148.86]}
                    rotation={[-Math.PI / 2, 0, 1.47]}
                    scale={0.11}
                  />
                  <mesh
                    name="Cube 85"
                    geometry={nodes['Cube 85'].geometry}
                    material={materials['Cube 85 Material']}
                    castShadow
                    receiveShadow
                    position={[-142.35, -229.37, 115.44]}
                    rotation={[-Math.PI / 2, 0, -1.31]}
                    scale={0.18}
                  />
                  <mesh
                    name="Cube 86"
                    geometry={nodes['Cube 86'].geometry}
                    material={materials['Cube 86 Material']}
                    castShadow
                    receiveShadow
                    position={[-151.45, -22.25, -153.6]}
                    rotation={[-Math.PI / 2, 0, -0.38]}
                    scale={0.15}
                  />
                  <mesh
                    name="Cube 87"
                    geometry={nodes['Cube 87'].geometry}
                    material={materials['Cube 87 Material']}
                    castShadow
                    receiveShadow
                    position={[22.67, -273.31, -409.56]}
                    rotation={[-Math.PI / 2, 0, -1.07]}
                    scale={0.1}
                  />
                </group>
                <group
                  name="Group 41"
                  position={[31.49, 134.26, -17.14]}
                  rotation={[-Math.PI, -0.05, -Math.PI]}
                  scale={0.14}
                >
                  <mesh
                    name="Cube 88"
                    geometry={nodes['Cube 88'].geometry}
                    material={materials['Cube 88 Material']}
                    castShadow
                    receiveShadow
                    position={[119.9, -472.12, 148.86]}
                    rotation={[-Math.PI / 2, 0, 1.47]}
                    scale={0.11}
                  />
                  <mesh
                    name="Cube 89"
                    geometry={nodes['Cube 89'].geometry}
                    material={materials['Cube 89 Material']}
                    castShadow
                    receiveShadow
                    position={[-142.35, -229.37, 115.44]}
                    rotation={[-Math.PI / 2, 0, -1.31]}
                    scale={0.18}
                  />
                  <mesh
                    name="Cube 810"
                    geometry={nodes['Cube 810'].geometry}
                    material={materials['Cube 810 Material']}
                    castShadow
                    receiveShadow
                    position={[-151.45, -22.25, -153.6]}
                    rotation={[-Math.PI / 2, 0, -0.38]}
                    scale={0.15}
                  />
                  <mesh
                    name="Cube 811"
                    geometry={nodes['Cube 811'].geometry}
                    material={materials['Cube 811 Material']}
                    castShadow
                    receiveShadow
                    position={[22.67, -273.31, -409.56]}
                    rotation={[-Math.PI / 2, 0, -1.07]}
                    scale={0.1}
                  />
                </group>
                <group
                  name="Group 3"
                  position={[-61.9, -58.21, -158.48]}
                  rotation={[-Math.PI, 1.29, -Math.PI]}
                  scale={0.14}
                >
                  <mesh
                    name="Cube 812"
                    geometry={nodes['Cube 812'].geometry}
                    material={materials['Cube 812 Material']}
                    castShadow
                    receiveShadow
                    position={[119.9, -472.12, 148.86]}
                    rotation={[-Math.PI / 2, 0, 1.47]}
                    scale={0.11}
                  />
                  <mesh
                    name="Cube 813"
                    geometry={nodes['Cube 813'].geometry}
                    material={materials['Cube 813 Material']}
                    castShadow
                    receiveShadow
                    position={[-142.35, -229.37, 115.44]}
                    rotation={[-Math.PI / 2, 0, -1.31]}
                    scale={0.18}
                  />
                  <mesh
                    name="Cube 814"
                    geometry={nodes['Cube 814'].geometry}
                    material={materials['Cube 814 Material']}
                    castShadow
                    receiveShadow
                    position={[-151.45, -22.25, -153.6]}
                    rotation={[-Math.PI / 2, 0, -0.38]}
                    scale={0.15}
                  />
                  <mesh
                    name="Cube 815"
                    geometry={nodes['Cube 815'].geometry}
                    material={materials['Cube 815 Material']}
                    castShadow
                    receiveShadow
                    position={[22.67, -273.31, -409.56]}
                    rotation={[-Math.PI / 2, 0, -1.07]}
                    scale={0.1}
                  />
                </group>
                <group
                  name="Group 61"
                  position={[84.19, -97.66, -135.18]}
                  rotation={[Math.PI, -1.13, Math.PI]}
                  scale={0.14}
                >
                  <mesh
                    name="Cube 816"
                    geometry={nodes['Cube 816'].geometry}
                    material={materials['Cube 816 Material']}
                    castShadow
                    receiveShadow
                    position={[119.9, -472.12, 148.86]}
                    rotation={[-Math.PI / 2, 0, 1.47]}
                    scale={0.11}
                  />
                  <mesh
                    name="Cube 817"
                    geometry={nodes['Cube 817'].geometry}
                    material={materials['Cube 817 Material']}
                    castShadow
                    receiveShadow
                    position={[-142.35, -229.37, 115.44]}
                    rotation={[-Math.PI / 2, 0, -1.31]}
                    scale={0.18}
                  />
                  <mesh
                    name="Cube 818"
                    geometry={nodes['Cube 818'].geometry}
                    material={materials['Cube 818 Material']}
                    castShadow
                    receiveShadow
                    position={[-151.45, -22.25, -153.6]}
                    rotation={[-Math.PI / 2, 0, -0.38]}
                    scale={0.15}
                  />
                  <mesh
                    name="Cube 819"
                    geometry={nodes['Cube 819'].geometry}
                    material={materials['Cube 819 Material']}
                    castShadow
                    receiveShadow
                    position={[22.67, -273.31, -409.56]}
                    rotation={[-Math.PI / 2, 0, -1.07]}
                    scale={0.1}
                  />
                </group>
                <group name="Group 51" position={[-125.35, -97.66, -57.49]} rotation={[0, -1.37, 0]} scale={0.14}>
                  <mesh
                    name="Cube 820"
                    geometry={nodes['Cube 820'].geometry}
                    material={materials['Cube 820 Material']}
                    castShadow
                    receiveShadow
                    position={[119.9, -472.12, 148.86]}
                    rotation={[-Math.PI / 2, 0, 1.47]}
                    scale={0.11}
                  />
                  <mesh
                    name="Cube 821"
                    geometry={nodes['Cube 821'].geometry}
                    material={materials['Cube 821 Material']}
                    castShadow
                    receiveShadow
                    position={[-142.35, -229.37, 115.44]}
                    rotation={[-Math.PI / 2, 0, -1.31]}
                    scale={0.18}
                  />
                  <mesh
                    name="Cube 822"
                    geometry={nodes['Cube 822'].geometry}
                    material={materials['Cube 822 Material']}
                    castShadow
                    receiveShadow
                    position={[-151.45, -22.25, -153.6]}
                    rotation={[-Math.PI / 2, 0, -0.38]}
                    scale={0.15}
                  />
                  <mesh
                    name="Cube 823"
                    geometry={nodes['Cube 823'].geometry}
                    material={materials['Cube 823 Material']}
                    castShadow
                    receiveShadow
                    position={[22.67, -273.31, -409.56]}
                    rotation={[-Math.PI / 2, 0, -1.07]}
                    scale={0.1}
                  />
                </group>
                <group name="Group 42" position={[4.71, -97.66, -7.5]} rotation={[0, 0.16, 0]} scale={0.14}>
                  <mesh
                    name="Cube 824"
                    geometry={nodes['Cube 824'].geometry}
                    material={materials['Cube 824 Material']}
                    castShadow
                    receiveShadow
                    position={[119.9, -472.12, 148.86]}
                    rotation={[-Math.PI / 2, 0, 1.47]}
                    scale={0.11}
                  />
                  <mesh
                    name="Cube 825"
                    geometry={nodes['Cube 825'].geometry}
                    material={materials['Cube 825 Material']}
                    castShadow
                    receiveShadow
                    position={[-142.35, -229.37, 115.44]}
                    rotation={[-Math.PI / 2, 0, -1.31]}
                    scale={0.18}
                  />
                  <mesh
                    name="Cube 826"
                    geometry={nodes['Cube 826'].geometry}
                    material={materials['Cube 826 Material']}
                    castShadow
                    receiveShadow
                    position={[-151.45, -22.25, -153.6]}
                    rotation={[-Math.PI / 2, 0, -0.38]}
                    scale={0.15}
                  />
                  <mesh
                    name="Cube 827"
                    geometry={nodes['Cube 827'].geometry}
                    material={materials['Cube 827 Material']}
                    castShadow
                    receiveShadow
                    position={[22.67, -273.31, -409.56]}
                    rotation={[-Math.PI / 2, 0, -1.07]}
                    scale={0.1}
                  />
                </group>
                <group name="Group 2" position={[-77.37, -97.66, -182.37]} rotation={[0, -1.18, 0]} scale={0.14}>
                  <mesh
                    name="Cube 828"
                    geometry={nodes['Cube 828'].geometry}
                    material={materials['Cube 828 Material']}
                    castShadow
                    receiveShadow
                    position={[119.9, -472.12, 148.86]}
                    rotation={[-Math.PI / 2, 0, 1.47]}
                    scale={0.11}
                  />
                  <mesh
                    name="Cube 829"
                    geometry={nodes['Cube 829'].geometry}
                    material={materials['Cube 829 Material']}
                    castShadow
                    receiveShadow
                    position={[-142.35, -229.37, 115.44]}
                    rotation={[-Math.PI / 2, 0, -1.31]}
                    scale={0.18}
                  />
                  <mesh
                    name="Cube 830"
                    geometry={nodes['Cube 830'].geometry}
                    material={materials['Cube 830 Material']}
                    castShadow
                    receiveShadow
                    position={[-151.45, -22.25, -153.6]}
                    rotation={[-Math.PI / 2, 0, -0.38]}
                    scale={0.15}
                  />
                  <mesh
                    name="Cube 831"
                    geometry={nodes['Cube 831'].geometry}
                    material={materials['Cube 831 Material']}
                    castShadow
                    receiveShadow
                    position={[22.67, -273.31, -409.56]}
                    rotation={[-Math.PI / 2, 0, -1.07]}
                    scale={0.1}
                  />
                </group>
              </group>
              <group name="Group" position={[-46.11, 2913.49, 20.67]} rotation={[0, -1.18, 0]} scale={3.33}>
                <mesh
                  name="Cube 11"
                  geometry={nodes['Cube 11'].geometry}
                  material={materials['Cube 11 Material']}
                  castShadow
                  receiveShadow
                  position={[158.6, -439.3, 98.87]}
                  rotation={[-Math.PI / 2, 0, -1.07]}
                  scale={0.23}
                />
                <mesh
                  name="Cube 10"
                  geometry={nodes['Cube 10'].geometry}
                  material={materials['Cube 10 Material']}
                  castShadow
                  receiveShadow
                  position={[-114.53, -548.22, 210.04]}
                  rotation={[-Math.PI / 2, 0, -1.07]}
                  scale={0.23}
                />
                <mesh
                  name="Cube 9"
                  geometry={nodes['Cube 9'].geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[-201.75, -439.3, -90.04]}
                  rotation={[-Math.PI / 2, 0, -1.07]}
                  scale={0.23}
                />
                <mesh
                  name="Cube 832"
                  geometry={nodes['Cube 832'].geometry}
                  material={materials['Cube 832 Material']}
                  castShadow
                  receiveShadow
                  position={[165.56, -439.3, -148.81]}
                  rotation={[-Math.PI / 2, 0, -1.07]}
                  scale={0.23}
                />
              </group>
              <mesh
                name="Cube 7"
                geometry={nodes['Cube 7'].geometry}
                material={materials['Cube 7 Material']}
                castShadow
                receiveShadow
                position={[352.97, 1044.39, 516.15]}
                rotation={[-Math.PI / 2, 0, 2.07]}
                scale={0.77}
              />
              <mesh
                name="Cube 6"
                geometry={nodes['Cube 6'].geometry}
                material={materials['Cube 6 Material']}
                castShadow
                receiveShadow
                position={[-519.91, 1044.39, 404.89]}
                rotation={[-Math.PI / 2, 0, 0.59]}
                scale={0.77}
              />
              <mesh
                name="Cube 5"
                geometry={nodes['Cube 5'].geometry}
                material={materials['Cube 5 Material']}
                castShadow
                receiveShadow
                position={[-550.19, 1044.39, -490.57]}
                rotation={[-Math.PI / 2, 0, -1.5]}
                scale={0.77}
              />
              <mesh
                name="Cube 4"
                geometry={nodes['Cube 4'].geometry}
                material={materials['Cube 4 Material']}
                castShadow
                receiveShadow
                position={[504.94, 1044.39, -474.63]}
                rotation={[-Math.PI / 2, 0, -1.07]}
                scale={0.77}
              />
              <group name="et" position={[78.28, 1810.66, 27.8]} scale={3.33}>
                <mesh
                  name="Cube 3"
                  geometry={nodes['Cube 3'].geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[-4.06, 75.55, -7.81]}
                  rotation={[-Math.PI / 2, 0, 0.88]}
                  scale={[0.55, 0.85, 0.55]}
                />
                <mesh
                  name="Cube 2"
                  geometry={nodes['Cube 2'].geometry}
                  material={materials['Cube 2 Material']}
                  castShadow
                  receiveShadow
                  position={[-4.06, 79.89, -7.81]}
                  rotation={[-Math.PI / 2, 0, 0.88]}
                  scale={[0.74, 1.16, 0.74]}
                />
                <mesh
                  name="Cube"
                  geometry={nodes.Cube.geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[-4.06, 73.3, -7.81]}
                  rotation={[-Math.PI / 2, 0, 0.88]}
                  scale={[0.86, 1.34, 0.86]}
                />
              </group>
              <group name="Group1" position={[-272.71, 222.45, 18.56]}>
                <mesh
                  name="Cube 51"
                  geometry={nodes['Cube 51'].geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[257.71, 1002.08, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[6, 6, 0.98]}
                />
                <mesh
                  name="Cube 41"
                  geometry={nodes['Cube 41'].geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[280.14, 645.19, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[5.01, 5.01, 0.49]}
                />
                <mesh
                  name="Cube 31"
                  geometry={nodes['Cube 31'].geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[257.71, -368.92, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[3.99, 3.99, 0.17]}
                />
                <group name="ızgara" position={[344.25, 1334.28, -32.83]}>
                  <mesh
                    name="Cube 71"
                    geometry={nodes['Cube 71'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[-222.07, 0, 889.46]}
                    rotation={[-Math.PI, -Math.PI / 2, 0]}
                    scale={[0.45, 0.45, 5.17]}
                  />
                  <mesh
                    name="Cube 61"
                    geometry={nodes['Cube 61'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[-222.07, 0, -861.66]}
                    rotation={[-Math.PI, -Math.PI / 2, 0]}
                    scale={[0.45, 0.45, 5.17]}
                  />
                  <mesh
                    name="Cube 833"
                    geometry={nodes['Cube 833'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[-994.78, 0, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[0.45, 0.45, 5.17]}
                  />
                  <mesh
                    name="Cube 13"
                    geometry={nodes['Cube 13'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[-718.87, 0, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[0.27, 0.27, 4.22]}
                  />
                  <mesh
                    name="Cube 12"
                    geometry={nodes['Cube 12'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[-15.96, 0, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[0.27, 0.27, 4.22]}
                  />
                  <mesh
                    name="Cube 131"
                    geometry={nodes['Cube 131'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[-478.56, 0, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[0.27, 0.27, 4.22]}
                  />
                  <mesh
                    name="Cube 111"
                    geometry={nodes['Cube 111'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[224.36, 0, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[0.27, 0.27, 4.22]}
                  />
                  <mesh
                    name="Cube 132"
                    geometry={nodes['Cube 132'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[-247.26, 0, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[0.27, 0.27, 4.22]}
                  />
                  <mesh
                    name="Cube 101"
                    geometry={nodes['Cube 101'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[455.66, 0, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[0.27, 0.27, 4.22]}
                  />
                  <mesh
                    name="Cube 21"
                    geometry={nodes['Cube 21'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[750.78, 0, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[0.45, 0.45, 5.17]}
                  />
                </group>
              </group>
              <group name="alt kavçuk 2" position={[5.28, 0, 53.18]} scale={[1.29, 8.53, 1.29]}>
                <group name="bacaklar" position={[0, 0, 0]} scale={1.01}>
                  <mesh
                    name="Cube 32"
                    geometry={nodes['Cube 32'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[275.38, 0, 240.97]}
                    rotation={[-Math.PI / 2, 0, -2.15]}
                    scale={0.45}
                  />
                  <mesh
                    name="Cube 22"
                    geometry={nodes['Cube 22'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[-283.39, 0, 240.97]}
                    rotation={[-Math.PI / 2, 0, 2.21]}
                    scale={0.45}
                  />
                  <mesh
                    name="Cube 33"
                    geometry={nodes['Cube 33'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[256.11, 0, -282.48]}
                    rotation={[-Math.PI / 2, 0, -0.67]}
                    scale={0.45}
                  />
                  <mesh
                    name="Cube1"
                    geometry={nodes.Cube1.geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[-302.66, 0, -282.48]}
                    rotation={[-Math.PI / 2, 0, 0.82]}
                    scale={0.45}
                  />
                </group>
              </group>
              <group name="alt kavçuk" position={[-0.65, -774.3, 3.69]} scale={1.82}>
                <mesh
                  name="Cube 42"
                  geometry={nodes['Cube 42'].geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[302.66, 0, 269.31]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.45}
                />
                <mesh
                  name="Cube 34"
                  geometry={nodes['Cube 34'].geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[272.99, 0, -268.36]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.45}
                />
                <mesh
                  name="Cube 43"
                  geometry={nodes['Cube 43'].geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[-302.66, 0, 274.15]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.45}
                />
                <mesh
                  name="Cube2"
                  geometry={nodes.Cube2.geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[-308.43, 0, -258.09]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.45}
                />
              </group>
            </group>
            <group name="ChefHat" position={[2.11, 200.84, -132.44]}>
              <mesh
                name="Sphere 4"
                geometry={nodes['Sphere 4'].geometry}
                material={materials['Sphere 4 Material']}
                castShadow
                receiveShadow
                position={[-56.82, 13.01, 28.72]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.97, 1, 1]}
              />
              <mesh
                name="Sphere 3"
                geometry={nodes['Sphere 3'].geometry}
                material={materials['Sphere 3 Material']}
                castShadow
                receiveShadow
                position={[51.54, 14.08, -53.5]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Sphere 2"
                geometry={nodes['Sphere 2'].geometry}
                material={materials['Sphere 2 Material']}
                castShadow
                receiveShadow
                position={[42.28, 19.38, 57.42]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Sphere"
                geometry={nodes.Sphere.geometry}
                material={materials['Sphere Material']}
                castShadow
                receiveShadow
                position={[-46.02, 29, -46.33]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Cylinder"
                geometry={nodes.Cylinder.geometry}
                material={materials['Cylinder Material']}
                castShadow
                receiveShadow
                position={[-7.6, -33.18, -3.13]}
              />
            </group>
            <group name="Penguin 2" position={[1.28, -94.68, -93.66]}>
              <group name="Body" position={[3.59, 0, 0]}>
                <mesh
                  name="MainBody"
                  geometry={nodes.MainBody.geometry}
                  material={materials['MainBody Material']}
                  castShadow
                  receiveShadow
                  position={[-4.16, 33.76, -37.31]}
                />
                <mesh
                  name="WhiteBelly"
                  geometry={nodes.WhiteBelly.geometry}
                  material={materials['WhiteBelly Material']}
                  castShadow
                  receiveShadow
                  position={[0.81, -64.34, 11.09]}
                  rotation={[0.85, 0, 0]}
                  scale={1}
                />
              </group>
              <group name="Beak" position={[-8.17, 68.35, 103.51]}>
                <mesh
                  name="Sphere 31"
                  geometry={nodes['Sphere 31'].geometry}
                  material={materials['Sphere 31 Material']}
                  castShadow
                  receiveShadow
                  position={[0, 0.03, -0.28]}
                />
                <mesh
                  name="Sphere 21"
                  geometry={nodes['Sphere 21'].geometry}
                  material={materials['Sphere 21 Material']}
                  castShadow
                  receiveShadow
                  position={[0, 0.03, -0.28]}
                />
              </group>
              <group name="Feet" position={[-5.63, -165.38, -34.19]}>
                <mesh
                  name="Sphere 32"
                  geometry={nodes['Sphere 32'].geometry}
                  material={materials['Sphere 32 Material']}
                  castShadow
                  receiveShadow
                  position={[-99.4, 3.77, 0]}
                  rotation={[0, 0, -0.31]}
                />
                <mesh
                  name="Sphere 22"
                  geometry={nodes['Sphere 22'].geometry}
                  material={materials['Sphere 22 Material']}
                  castShadow
                  receiveShadow
                  position={[101.86, -7.69, 0]}
                  rotation={[0, 0, 0.2]}
                  scale={1}
                />
              </group>
              <group name="Arms" position={[0, -4.56, -39.23]}>
                <mesh
                  name="Cube 23"
                  geometry={nodes['Cube 23'].geometry}
                  material={materials['Cube 23 Material']}
                  castShadow
                  receiveShadow
                  position={[-168.24, 0.26, 17.62]}
                  rotation={[0, 0, -0.59]}
                />
                <mesh
                  name="Cube3"
                  geometry={nodes.Cube3.geometry}
                  material={materials['Cube3 Material']}
                  castShadow
                  receiveShadow
                  position={[164.23, -5.05, 17.62]}
                  rotation={[0, 0, 0.7]}
                />
              </group>
              <group name="Blush" position={[-14.19, 65.69, 107.41]}>
                <mesh
                  name="Ellipse 3"
                  geometry={nodes['Ellipse 3'].geometry}
                  material={materials['Ellipse 3 Material']}
                  castShadow
                  receiveShadow
                  position={[74.11, -4.52, -44.86]}
                  rotation={[-0.07, 0.51, 0.14]}
                  scale={1}
                />
                <mesh
                  name="Ellipse 2"
                  geometry={nodes['Ellipse 2'].geometry}
                  material={materials['Ellipse 2 Material']}
                  castShadow
                  receiveShadow
                  position={[-82.82, -3.15, -41.9]}
                  rotation={[0, -0.71, 0]}
                />
              </group>
              <group name="Eyes" position={[-21.03, 96.82, 111.27]} scale={[1, 0.99, 1]}>
                <mesh
                  name="Sphere 33"
                  geometry={nodes['Sphere 33'].geometry}
                  material={materials['Sphere 33 Material']}
                  castShadow
                  receiveShadow
                  position={[74.11, 5.24, -29.78]}
                />
                <mesh
                  name="Sphere 23"
                  geometry={nodes['Sphere 23'].geometry}
                  material={materials['Sphere 23 Material']}
                  castShadow
                  receiveShadow
                  position={[-55.98, 6.3, -40.14]}
                />
              </group>
            </group>
          </group>
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[200, 718.52, 300]}
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
