/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import { useRef } from 'react'
import { useFrame } from 'react-three-fiber';

export default function SpeechBubbles({ ...props }) {

    const group = useRef();

    useFrame(() => {
        if (group.current) {
            group.current.rotation.y += 0.005;
        }
    })

    
  const { nodes, materials } = useSpline('https://prod.spline.design/gc2ZWxuf371uoiZB/scene.splinecode')
  return (
    <>
      {/* <color attach="background" args={['#e7e7e7']} /> */}
      <group {...props} dispose={null}>
        <scene name="Scene">
          <group name="UpperRightTextBubble 3" position={[45.69, 100.03, 15.73]} rotation={[0, 0, -0.17]} scale={0.59}>
            <mesh
              name="Cube 2"
              geometry={nodes['Cube 2'].geometry}
              material={materials['Cube 2 Material']}
              castShadow
              receiveShadow
              position={[-17.29, -23.25, -0.19]}
              rotation={[0, 0, -0.82]}
            />
            <mesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials['Cube Material']}
              castShadow
              receiveShadow
              position={[0, 4.7, -0.11]}
            />
            <group name="TextDots" position={[6.71, -1.31, 0.08]}>
              <group name="Dots" position={[-0.24, 7.21, -8.51]} rotation={[0, 0, 0]} scale={[1, 1, 0.99]}>
                <mesh
                  name="Sphere 3"
                  geometry={nodes['Sphere 3'].geometry}
                  material={materials['Sphere 3 Material']}
                  castShadow
                  receiveShadow
                  position={[15.15, 0, 0]}
                />
                <mesh
                  name="Sphere 2"
                  geometry={nodes['Sphere 2'].geometry}
                  material={materials['Sphere 2 Material']}
                  castShadow
                  receiveShadow
                  position={[-6.11, 0, 0]}
                />
                <mesh
                  name="Sphere"
                  geometry={nodes.Sphere.geometry}
                  material={materials['Sphere Material']}
                  castShadow
                  receiveShadow
                  position={[-27.58, 0, 0]}
                />
              </group>
              <group name="Dots1" position={[-0.24, 7.21, 7.8]} scale={[1, 1, 0.99]}>
                <mesh
                  name="Sphere 31"
                  geometry={nodes['Sphere 31'].geometry}
                  material={materials['Sphere 31 Material']}
                  castShadow
                  receiveShadow
                  position={[15.15, 0, 0]}
                />
                <mesh
                  name="Sphere 21"
                  geometry={nodes['Sphere 21'].geometry}
                  material={materials['Sphere 21 Material']}
                  castShadow
                  receiveShadow
                  position={[-6.11, 0, 0]}
                />
                <mesh
                  name="Sphere1"
                  geometry={nodes.Sphere1.geometry}
                  material={materials['Sphere1 Material']}
                  castShadow
                  receiveShadow
                  position={[-27.58, 0, 0]}
                />
              </group>
            </group>
          </group>
          <group name="UpperLeftTextBubble 2" position={[-61.59, 80.69, 13.75]} rotation={[0, 0, 0.19]} scale={0.47}>
            <mesh
              name="Cube 21"
              geometry={nodes['Cube 21'].geometry}
              material={materials['Cube 21 Material']}
              castShadow
              receiveShadow
              position={[10.16, -24.26, -0.48]}
              rotation={[0, 0, -0.59]}
            />
            <mesh
              name="Cube1"
              geometry={nodes.Cube1.geometry}
              material={materials['Cube1 Material']}
              castShadow
              receiveShadow
              position={[0, 4.55, -0.11]}
            />
            <group name="TextDots1" position={[6.71, -1.31, 0.08]}>
              <group name="Dots2" position={[-0.24, 7.21, -8.07]} scale={[1, 1, 0.99]}>
                <mesh
                  name="Sphere 32"
                  geometry={nodes['Sphere 32'].geometry}
                  material={materials['Sphere 32 Material']}
                  castShadow
                  receiveShadow
                  position={[15.15, 0, 0]}
                />
                <mesh
                  name="Sphere 22"
                  geometry={nodes['Sphere 22'].geometry}
                  material={materials['Sphere 22 Material']}
                  castShadow
                  receiveShadow
                  position={[-6.11, 0, 0]}
                />
                <mesh
                  name="Sphere2"
                  geometry={nodes.Sphere2.geometry}
                  material={materials['Sphere2 Material']}
                  castShadow
                  receiveShadow
                  position={[-27.58, 0, 0]}
                />
              </group>
              <group name="Dots3" position={[-0.24, 7.21, 7.8]} scale={[1, 1, 0.99]}>
                <mesh
                  name="Sphere 33"
                  geometry={nodes['Sphere 33'].geometry}
                  material={materials['Sphere 33 Material']}
                  castShadow
                  receiveShadow
                  position={[15.15, 0, 0]}
                />
                <mesh
                  name="Sphere 23"
                  geometry={nodes['Sphere 23'].geometry}
                  material={materials['Sphere 23 Material']}
                  castShadow
                  receiveShadow
                  position={[-6.11, 0, 0]}
                />
                <mesh
                  name="Sphere3"
                  geometry={nodes.Sphere3.geometry}
                  material={materials['Sphere3 Material']}
                  castShadow
                  receiveShadow
                  position={[-27.58, 0, 0]}
                />
              </group>
            </group>
          </group>
          <group ref={group} name="MainTextBubble" position={[-9.94, 8, 22.7]} scale={1.3}>
            <mesh
              name="Cube 22"
              geometry={nodes['Cube 22'].geometry}
              material={materials['Cube 22 Material']}
              castShadow
              receiveShadow
              position={[10.1, -23.9, -0.82]}
              rotation={[0, 0, -0.59]}
            />
            <mesh
              name="Cube2"
              geometry={nodes.Cube2.geometry}
              material={materials['Cube2 Material']}
              castShadow
              receiveShadow
              position={[0, 4.55, -0.11]}
            />
            <group name="TextDots2" position={[6.71, -1.31, 0.08]}>
              <group name="Dots4" position={[-0.24, 7.21, -8.73]} scale={[1, 1, 0.99]}>
                <mesh
                  name="Sphere 34"
                  geometry={nodes['Sphere 34'].geometry}
                  material={materials['Sphere 34 Material']}
                  castShadow
                  receiveShadow
                  position={[15.15, 0, 0]}
                />
                <mesh
                  name="Sphere 24"
                  geometry={nodes['Sphere 24'].geometry}
                  material={materials['Sphere 24 Material']}
                  castShadow
                  receiveShadow
                  position={[-6.11, 0, 0]}
                />
                <mesh
                  name="Sphere4"
                  geometry={nodes.Sphere4.geometry}
                  material={materials['Sphere4 Material']}
                  castShadow
                  receiveShadow
                  position={[-27.58, 0, 0]}
                />
              </group>
              <group name="Dots5" position={[-0.24, 7.21, 7.8]} scale={[1, 1, 0.99]}>
                <mesh
                  name="Sphere 35"
                  geometry={nodes['Sphere 35'].geometry}
                  material={materials['Sphere 35 Material']}
                  castShadow
                  receiveShadow
                  position={[15.15, 0, 0]}
                />
                <mesh
                  name="Sphere 25"
                  geometry={nodes['Sphere 25'].geometry}
                  material={materials['Sphere 25 Material']}
                  castShadow
                  receiveShadow
                  position={[-6.11, 0, 0]}
                />
                <mesh
                  name="Sphere5"
                  geometry={nodes.Sphere5.geometry}
                  material={materials['Sphere5 Material']}
                  castShadow
                  receiveShadow
                  position={[-27.58, 0, 0]}
                />
              </group>
            </group>
          </group>
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
